### PR TITLE
feat, fixes, refactor: fixing page 

### PR DESCRIPTION
**Pull request by dr-nefardio3058**
### _I. Refactoring and organizing files:_ ###

This PR is a reference to the issue #2.

**What I did in this PR (2 commits):**

- Updated path to favicons (all browsers)
- Organized all the files in folders
- Merged js and css files all into 2 separated files, instead of 6.
- Added some Google Fonts
- Corrected indentation in all files (4 spaces)
- Clean some code by adding spaces and comments.
- Changed carrousel arrows styles
- Deleted .hintrc and "backups.txt" files. (among other changes)

What will I do next: (other PR)

- [x] Make navbar sticky
- [x] Add floating labels to form
- [x] Try to make page responsive
- [x] Work on the portfolio section

See you, Jeremy. Have a good day. :octocat:

### CODE REVIEW

**Comment by dr-nefardio3058** [comment]
PR readyy! :shipit: Let me know your thoughts! Will start the 2nd one soon!

**Comment by jge162** [comment]
> PR readyy! :shipit: Let me know your thoughts! Will start the 2nd one soon!

Ok I will take a look after class tonight. Thanks.

**Comment by jge162** [comment]
Thank you for all the great suggestions but this is not a repo I plan to maintain or update. So beats to you and all your efforts.

**Review by dr-nefardio3058 — COMMENTED** [review]
👍

**Pull request closed without merging**
